version: '3.10'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code

  database:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: '${NAME}'
      MYSQL_USER: '${USERNAME}'
      MYSQL_PASSWORD: '${PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${PASSWORD}'
    ports:
      - '3306:3306'

